### ISSUE TITLE
Improvement enumeration paragraphs layer

### ISSUE THREAD

**Issue by AnnickvOol** [DeNederlandscheBank/nafigator#34]
* nafigator version: 0.1.46
* Python version: 3.8
* Operating System: windows

### Description

Enumeration paragraphs layer is not in line with enumeration in other layers (sentences, text and terms layer). This is confusing. 

Enumeration in sentences layer:
naf.sentences[0] includes 'sent':['1']
naf.sentences[1] includes 'sent':['2']
etc.
The same enumeration holds for terms and text layer. 

Enumeration in paragraphs layer:
naf.paragraphs[1] includes 'para':['1']
naf.sentences[2] includes 'para':['2']

It would be more logical if the enumeration is the same for all layers.

**Comment by wjwillemse** [comment]
Aligned paragraphs and sentences: naf.paragraph[0] now includes 'para': [1], to align it with naf.sentences. If no para data is included in the naf document then an empty list is returned. This is solved in version v0.1.47.
